# haberci toml config file

title = "Haberci config file"

[Mail]
server = "mail.example.com"
port = 587
username = "notify@example.com"
password = "P@ssw@rd"
from = "notify@example.com"

[Yts]
enabled = "yes" # Set "no" to disabled
subject = "Haberci Auto Message"
# Multi recipients example [ "name@example.com", "name2@example.com" ] 
torecipients = [ "name@example.com" ]
bccrecipients = [ ]
pageLimit = "10"

