# haberci toml config file

title = "Haberci config file"

[mail]
server = "mail.example.com"
port = 587
username = "notify@example.com"
password = "P@ssw@rd"
from = "notify@example.com"

[yts]
subject = "Haberci Auto Message"
# Multi recipients example [ "name@example.com", "name2@example.com" ] 
recipients = [ "name@example.com" ]
pageLimit = "10"

